using System.Text;
using ZombiesWP7.menu;

namespace IMAK3Z0MB1EGAEM.menu;

public class Credits : MenuLevel
{
	public Credits()
	{
		title = "cr3d1ts";
		infos = new StringBuilder[115]
		{
			new StringBuilder("Z0MB1ES!!!1 (on teh ph0n3)"),
			new StringBuilder(""),
			new StringBuilder("by James Silva"),
			new StringBuilder("and Ska Studios!"),
			new StringBuilder(""),
			new StringBuilder("Ska Studios is"),
			new StringBuilder(""),
			new StringBuilder("-= Lead Dishwasher =-"),
			new StringBuilder("James Silva"),
			new StringBuilder(""),
			new StringBuilder("-= Marketing Coordinator =-"),
			new StringBuilder("Dustin Burg"),
			new StringBuilder(""),
			new StringBuilder("-= Art Unicorn =-"),
			new StringBuilder("Michelle Juett"),
			new StringBuilder(""),
			new StringBuilder(""),
			new StringBuilder("Special Thanks:"),
			new StringBuilder(""),
			new StringBuilder("The roughly 300,000 peoples that"),
			new StringBuilder("PLAED A GAM3 W1TH Z0MB1ES 1N IT!!1"),
			new StringBuilder(""),
			new StringBuilder(""),
			new StringBuilder("Microsoft Studios"),
			new StringBuilder(""),
			new StringBuilder("Xbox LIVE Arcade Team"),
			new StringBuilder(""),
			new StringBuilder("-= Producer =-"),
			new StringBuilder("Stuart Platt"),
			new StringBuilder(""),
			new StringBuilder("-= SDET Lead =-"),
			new StringBuilder("Dan Smith"),
			new StringBuilder(""),
			new StringBuilder("-= Test Lead =-"),
			new StringBuilder("Tor Ulstein"),
			new StringBuilder(""),
			new StringBuilder("-= Release Management =-"),
			new StringBuilder("Josh Mulanax"),
			new StringBuilder("Shogo Ishii (Teksystems)"),
			new StringBuilder(""),
			new StringBuilder("-= Lead Producer =-"),
			new StringBuilder("Kevin Hathaway"),
			new StringBuilder(""),
			new StringBuilder("-= Executive Producer =-"),
			new StringBuilder("Mark Coates"),
			new StringBuilder(""),
			new StringBuilder("-= Director, XBLA Publishing =-"),
			new StringBuilder("Ted Woolsey"),
			new StringBuilder(""),
			new StringBuilder("-= Business Development =-"),
			new StringBuilder("Cherie Lutz"),
			new StringBuilder(""),
			new StringBuilder("-= Portfolio Director =-"),
			new StringBuilder("Chris Charla"),
			new StringBuilder(""),
			new StringBuilder("-= Product Manager =-"),
			new StringBuilder("Daniel McConnell"),
			new StringBuilder(""),
			new StringBuilder("-= Marketing =-"),
			new StringBuilder("Michael Wolf"),
			new StringBuilder("John Dongelmans"),
			new StringBuilder(""),
			new StringBuilder("-= Milestone Acceptance Tester =-"),
			new StringBuilder("Brian McCarty (Xtreme Consulting Group Inc)"),
			new StringBuilder(""),
			new StringBuilder("-= Special Thanks =-"),
			new StringBuilder("Oliver Miyashita"),
			new StringBuilder("Kevin Salcedo"),
			new StringBuilder("Matt Golz"),
			new StringBuilder("David Boker"),
			new StringBuilder(""),
			new StringBuilder(""),
			new StringBuilder("Experis Test Team"),
			new StringBuilder(""),
			new StringBuilder("-= Test Lead =-"),
			new StringBuilder("Lloyd Bell"),
			new StringBuilder(""),
			new StringBuilder("-= Software Test Engineers =-"),
			new StringBuilder("Russell Allen"),
			new StringBuilder("Allyson Burk"),
			new StringBuilder("Nick Hardy"),
			new StringBuilder("Kimberly Lyles"),
			new StringBuilder("Chris Merritt"),
			new StringBuilder("Eric Ranz"),
			new StringBuilder(""),
			new StringBuilder("-= Software Developer Test Engineer =-"),
			new StringBuilder("Valeriy Novytskyy"),
			new StringBuilder(""),
			new StringBuilder("-= Test Associates =-"),
			new StringBuilder("Josh Breese"),
			new StringBuilder("Stephen Chase"),
			new StringBuilder("April Culberson"),
			new StringBuilder("Jason Fox"),
			new StringBuilder("Matthew Howells"),
			new StringBuilder("Alan Hume"),
			new StringBuilder("Kevin Lourigan"),
			new StringBuilder("Risё Lugo"),
			new StringBuilder("Isaac Price"),
			new StringBuilder("Masha Reutovski"),
			new StringBuilder("Jonathan Tote"),
			new StringBuilder("Gillian Williams"),
			new StringBuilder("Marc Williams"),
			new StringBuilder("Jeffrey Woito"),
			new StringBuilder("Tyler Young"),
			new StringBuilder("Kim YoungMin"),
			new StringBuilder("Jae Yslas"),
			new StringBuilder(""),
			new StringBuilder(""),
			new StringBuilder("-=-"),
			new StringBuilder(""),
			new StringBuilder(""),
			new StringBuilder("Z0MB1ES!!!1 (on teh ph0n3)"),
			new StringBuilder("Version 1.0.0.0"),
			new StringBuilder("www.ska-studios.com"),
			new StringBuilder("")
		};
		scrolling = true;
		scrollMax = 1926f;
		item = new MenuItem[0];
	}

	public override void Cancel()
	{
		active = false;
		Menu.menuLevel[3].active = true;
		base.Cancel();
	}
}
